Repository Long182k/E-Commercial-Mobile, pull requests merged in 2024-10, with the labels that each got.

#1 feat: rendering products UI
  .idea/vcs.xml
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/ProductRepositoryImplement.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/ProductRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetProductUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/theme/Color.kt
  presentation/src/main/java/com/example/e_commercial/ui/theme/Theme.kt
  presentation/src/main/java/com/example/e_commercial/ui/theme/Type.kt
  presentation/src/main/res/drawable/ic_profile.jpg
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/drawable/notification.xml
  presentation/src/main/res/font/poppins.xml
  presentation/src/main/res/font/poppins_black.ttf
  presentation/src/main/res/font/poppins_black_italic.ttf
  presentation/src/main/res/font/poppins_bold.ttf
  presentation/src/main/res/font/poppins_bold_italic.ttf
  presentation/src/main/res/font/poppins_extra_bold.ttf
  presentation/src/main/res/font/poppins_extra_bold_italic.ttf
  presentation/src/main/res/font/poppins_extra_light.ttf
  presentation/src/main/res/font/poppins_extra_light_italic.ttf
  presentation/src/main/res/font/poppins_italic.ttf
  presentation/src/main/res/font/poppins_light.ttf
  presentation/src/main/res/font/poppins_light_italic.ttf
  presentation/src/main/res/font/poppins_medium.ttf
  presentation/src/main/res/font/poppins_medium_italic.ttf
  presentation/src/main/res/font/poppins_regular.ttf
  presentation/src/main/res/font/poppins_semi_bold.ttf
  presentation/src/main/res/font/poppins_semi_bold_italic.ttf
  presentation/src/main/res/font/poppins_thin.ttf
  presentation/src/main/res/font/poppins_thin_italic.ttf
Labels: feature

#2 fix: change loading icon and add product category
  data/src/main/java/com/example/data/di/RepositoryModule.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/CategoryRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/CategoryRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetCategoriesUseCase.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeViewModel.kt
Labels: enhancement

#4 change category response and add animation rendering
  .idea/deploymentTargetSelector.xml
  data/src/main/java/com/example/data/model/CategoryDataModel.kt
  data/src/main/java/com/example/data/model/response/CategoriesListResponse.kt
  data/src/main/java/com/example/data/model/response/ProductListResponse.kt
  domain/src/main/java/com/example/domain/model/CategoriesListModel.kt
  domain/src/main/java/com/example/domain/model/Category.kt
  domain/src/main/java/com/example/domain/model/ProductListModel.kt
Labels: enhancement, feature

#5 edit: change product source
  .idea/deploymentTargetSelector.xml
  data/src/main/java/com/example/data/di/NetworkModule.kt
  data/src/main/java/com/example/data/model/DataProductModel.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/CategoryRepositoryImplement.kt
  data/src/main/java/com/example/data/repository/ProductRepositoryImplement.kt
  domain/src/main/java/com/example/domain/model/Product.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/CategoryRepository.kt
  domain/src/main/java/com/example/domain/repository/ProductRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetProductUseCase.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeViewModel.kt
Labels: enhancement, feature

#6 feat: setting up navigator between products
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/model/UIProductModel.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/navigation/ProductNavType.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
Labels: enhancement, feature

#7 feat: setup product detail screen
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsViewModel.kt
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_favorite.xml
  presentation/src/main/res/drawable/ic_star.xml
Labels: feature

#8 feat: implement add product to cart feature & cart UI
  data/src/main/java/com/example/data/di/RepositoryModule.kt
  data/src/main/java/com/example/data/model/request/AddToCartRequest.kt
  data/src/main/java/com/example/data/model/response/CartItem.kt
  data/src/main/java/com/example/data/model/response/CartResponse.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/CartRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/model/CartItemModel.kt
  domain/src/main/java/com/example/domain/model/CartModel.kt
  domain/src/main/java/com/example/domain/model/request/AddCartRequestModel.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/CartRepository.kt
  domain/src/main/java/com/example/domain/usecase/AddToCartUseCase.kt
  domain/src/main/java/com/example/domain/usecase/GetCartUseCase.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsViewModel.kt
  presentation/src/main/res/drawable/ic_add.xml
  presentation/src/main/res/drawable/ic_delete.xml
  presentation/src/main/res/drawable/ic_subtract.xml
Labels: feature

#9 feat: increase & decrease quantity and remove item in cart
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  data/src/main/java/com/example/data/di/NetworkModule.kt
  data/src/main/java/com/example/data/model/request/AddToCartRequest.kt
  data/src/main/java/com/example/data/model/response/CartItem.kt
  data/src/main/java/com/example/data/model/response/CartSummaryResponse.kt
  data/src/main/java/com/example/data/model/response/Summary.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/CartRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/model/CartItemModel.kt
  domain/src/main/java/com/example/domain/model/CartSummary.kt
  domain/src/main/java/com/example/domain/model/SummaryData.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/CartRepository.kt
  domain/src/main/java/com/example/domain/usecase/CartSummaryUseCase.kt
  domain/src/main/java/com/example/domain/usecase/DeleteProductUseCase.kt
  domain/src/main/java/com/example/domain/usecase/UpdateQuantityUseCase.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/model/UIProductModel.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/navigation/ProductNavType.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryViewModel.kt
Labels: enhancement

#10 feature/orders & user_address
  data/src/main/java/com/example/data/di/RepositoryModule.kt
  data/src/main/java/com/example/data/model/request/AddressDataModel.kt
  data/src/main/java/com/example/data/model/response/OrderD.kt
  data/src/main/java/com/example/data/model/response/OrderItem.kt
  data/src/main/java/com/example/data/model/response/OrderListData.kt
  data/src/main/java/com/example/data/model/response/OrdersListResponse.kt
  data/src/main/java/com/example/data/model/response/PlaceOrderResponse.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/OrderRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/model/AddressDomainModel.kt
  domain/src/main/java/com/example/domain/model/OrderProductItem.kt
  domain/src/main/java/com/example/domain/model/OrdersData.kt
  domain/src/main/java/com/example/domain/model/OrdersListModel.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/OrderRepository.kt
  domain/src/main/java/com/example/domain/usecase/OrderListUseCase.kt
  domain/src/main/java/com/example/domain/usecase/PlaceOrderUseCase.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/model/UserAddress.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/navigation/UserAddressNavType.kt
  presentation/src/main/java/com/example/e_commercial/navigation/UserAddressRouteWrapper.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/user_address/UserAddressScreen.kt
  presentation/src/main/java/com/example/e_commercial/utils/CurrencyUtils.kt
  presentation/src/main/res/drawable/ic_address.xml
  presentation/src/main/res/drawable/ic_orders.xml
  presentation/src/main/res/drawable/ic_success.xml
Labels: enhancement

#11 feature/login & register & update CartScreen position
  .idea/misc.xml
  data/src/main/java/com/example/data/di/RepositoryModule.kt
  data/src/main/java/com/example/data/model/request/LoginRequest.kt
  data/src/main/java/com/example/data/model/request/RegisterRequest.kt
  data/src/main/java/com/example/data/model/response/UserAuthResponse.kt
  data/src/main/java/com/example/data/model/response/UserResponse.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/CartRepositoryImplement.kt
  data/src/main/java/com/example/data/repository/OrderRepositoryImplement.kt
  data/src/main/java/com/example/data/repository/UserRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/model/Product.kt
  domain/src/main/java/com/example/domain/model/UserDomainModel.kt
  domain/src/main/java/com/example/domain/model/request/AddCartRequestModel.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/CartRepository.kt
  domain/src/main/java/com/example/domain/repository/OrderRepository.kt
  domain/src/main/java/com/example/domain/repository/UserRepository.kt
  domain/src/main/java/com/example/domain/usecase/AddToCartUseCase.kt
  domain/src/main/java/com/example/domain/usecase/CartSummaryUseCase.kt
  domain/src/main/java/com/example/domain/usecase/DeleteProductUseCase.kt
  domain/src/main/java/com/example/domain/usecase/GetCartUseCase.kt
  domain/src/main/java/com/example/domain/usecase/LoginUseCase.kt
  domain/src/main/java/com/example/domain/usecase/OrderListUseCase.kt
  domain/src/main/java/com/example/domain/usecase/PlaceOrderUseCase.kt
  domain/src/main/java/com/example/domain/usecase/RegisterUseCase.kt
  domain/src/main/java/com/example/domain/usecase/UpdateQuantityUseCase.kt
  presentation/src/main/java/com/example/e_commercial/EcommercialSession.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/LoginScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/LoginViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/register/RegisterScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/register/RegisterViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryViewModel.kt
  presentation/src/main/res/drawable/ic_cart.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#13 update/ui-layout & add/button-back-to-HomeScreen
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/LoginScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/register/RegisterScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/user_address/UserAddressScreen.kt
  presentation/src/main/res/drawable/ic_add.xml
  presentation/src/main/res/drawable/ic_cart.xml
  presentation/src/main/res/drawable/ic_discount.xml
  presentation/src/main/res/drawable/ic_order.xml
  presentation/src/main/res/drawable/ic_shipping.xml
  presentation/src/main/res/drawable/ic_subtotal.xml
  presentation/src/main/res/drawable/ic_tax.xml
  presentation/src/main/res/drawable/ic_total.xml
Labels: enhancement
