Repository Long182k/E-Commercial-Mobile, pull requests merged in 2025-01, with the labels that each got.

#24 refactor the code & add dismiss button
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/LoginViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/cart/CartViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/notifications/NotificationScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/notifications/NotificationViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryScreen.kt
  presentation/src/main/res/drawable/ic_waiting.png
Labels: enhancement

#28 feature/forgot-password
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/UserRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/UserRepository.kt
  domain/src/main/java/com/example/domain/usecase/ForgotPasswordUseCase.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/ViewModelModule.kt
  presentation/src/main/java/com/example/e_commercial/navigation/NavRoutes.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/LoginScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/forgotpassword/ForgotPasswordScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/forgotpassword/ForgotPasswordViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#29 update/change-password and add/validation
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileViewModel.kt
Labels: enhancement

#30 update/forgot-password
  presentation/src/main/java/com/example/e_commercial/ui/feature/account/login/forgotpassword/ForgotPasswordScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileViewModel.kt
Labels: enhancement

#31 Feature/implement edit profile feature
  .idea/deploymentTargetSelector.xml
  data/src/main/java/com/example/data/model/response/EditProfileResponse.kt
  data/src/main/java/com/example/data/model/response/UserResponse.kt
  data/src/main/java/com/example/data/network/NetworkServiceImplement.kt
  data/src/main/java/com/example/data/repository/UserRepositoryImplement.kt
  domain/src/main/java/com/example/domain/di/UseCaseModule.kt
  domain/src/main/java/com/example/domain/model/ProfileFormData.kt
  domain/src/main/java/com/example/domain/model/UserDomainModel.kt
  domain/src/main/java/com/example/domain/network/NetworkService.kt
  domain/src/main/java/com/example/domain/repository/UserRepository.kt
  domain/src/main/java/com/example/domain/usecase/EditProfileUseCase.kt
  domain/src/main/java/com/example/domain/usecase/UpdateUserDetailsUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/ic_app-playstore.png
  presentation/src/main/java/com/example/e_commercial/ECommercialApp.kt
  presentation/src/main/java/com/example/e_commercial/EcommercialSession.kt
  presentation/src/main/java/com/example/e_commercial/MainActivity.kt
  presentation/src/main/java/com/example/e_commercial/di/AppModule.kt
  presentation/src/main/java/com/example/e_commercial/di/ImageLoaderModule.kt
  presentation/src/main/java/com/example/e_commercial/ui/SharedViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/product_details/ProductDetailsViewModel.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileViewModel.kt
  presentation/src/main/res/drawable/ic_app.webp
  presentation/src/main/res/drawable/ic_app_background.xml
  presentation/src/main/res/drawable/ic_app_foreground.webp
  presentation/src/main/res/drawable/ic_app_round.webp
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/xml/network_security_config.xml
Labels: enhancement

#32 Feature/implement edit profile feature
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/summary/CartSummaryScreen.kt
  presentation/src/main/res/drawable/ic_order_confirm.xml
Labels: enhancement

#33 enhance: re-implement order history screen
  data/src/main/java/com/example/data/model/response/OrderListData.kt
  domain/src/main/java/com/example/domain/model/OrdersData.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersViewModel.kt
Labels: enhancement

#34 edit: re-format order date
  presentation/src/main/java/com/example/e_commercial/ui/feature/notifications/NotificationScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/orders/OrdersScreen.kt
Labels: enhancement

#35 edit: fix user session and change default user image
  presentation/src/main/java/com/example/e_commercial/EcommercialSession.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/home/HomeScreen.kt
  presentation/src/main/java/com/example/e_commercial/ui/feature/profile/ProfileScreen.kt
  presentation/src/main/res/drawable/ic_default_img.jpg
Labels: enhancement

#36 Create README.md
  README.md
Labels: documentation, enhancement, help wanted, good first issue
